### ISSUE TITLE
Question: How to build/run docker image on OSX

### ISSUE THREAD

**Issue by epsilonhalbe** [jim60105/docker-whisperX#20]
I tried to run the docker image (base-en) on OSX both from a local build as well from a pulled image.

I tried to build with `--build-arg TARGETPLATFORM="linux/arm64` and without.

But I end up with:
```
docker run --gpus all -it -v ".:/app" ghcr.io/jim60105/whisperx:base-en     -- --output_format srt audio.m4a
docker: Error response from daemon: could not select device driver "" with capabilities: [[gpu]].
```
and if I omit the GPU flag

```
docker run -it -v ".:/app" ghcr.io/jim60105/whisperx:base-en     -- --output_format srt audio.m4a
Traceback (most recent call last):
  File "/venv/bin/whisperx", line 5, in <module>
    from whisperx.transcribe import cli
  File "/venv/lib/python3.10/site-packages/whisperx/__init__.py", line 1, in <module>
    from .transcribe import load_model
  File "/venv/lib/python3.10/site-packages/whisperx/transcribe.py", line 9, in <module>
    from .alignment import align, load_align_model
  File "/venv/lib/python3.10/site-packages/whisperx/alignment.py", line 11, in <module>
    import torchaudio
  File "/venv/lib/python3.10/site-packages/torchaudio/__init__.py", line 1, in <module>
    from . import (  # noqa: F401
  File "/venv/lib/python3.10/site-packages/torchaudio/_extension/__init__.py", line 45, in <module>
    _load_lib("libtorchaudio")
  File "/venv/lib/python3.10/site-packages/torchaudio/_extension/utils.py", line 64, in _load_lib
    torch.ops.load_library(path)
  File "/venv/lib/python3.10/site-packages/torch/_ops.py", line 852, in load_library
    ctypes.CDLL(path)
  File "/usr/local/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libgomp.so.1: cannot open shared object file: No such file or directory
```

I managed to build and run whisperx locally but I'd prefer to use docker containers instead of garbling up my system with conda and python

**Comment by jim60105** [comment]
Thank you for your PR.

For your issue about `could not select device driver "" with capabilities: [[gpu]]`, please try again after completing this guide:
https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html
