### ISSUE TITLE
Permission denied: '/.cache'

### ISSUE THREAD

**Issue by randyburden** [jim60105/docker-whisperX#27]
I'm receiving the following error using commit 94507c70fde08ef3c83bbfb293e50b44193aa8de: `PermissionError: [Errno 13] Permission denied: '/.cache'`

Reverting to prior commit 1fb00649fb9beb9ffd2d25ec259ef53f746eb478 fixed the issue for me.

Steps to reproduce using pre-built Docker image: 
```bash 
docker run --gpus all -it -v ".:/app" ghcr.io/jim60105/whisperx:small-en -- --diarize --hf_token "XXXXX" audio.mp3

Matplotlib created a temporary cache directory at /tmp/matplotlib-0qeq3jjn because the default path (/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
/venv/lib/python3.10/site-packages/pyannote/audio/core/io.py:43: UserWarning: torchaudio._backend.set_audio_backend has been deprecated. With dispatcher enabled, this function is no-op. You can remove the function call.
  torchaudio.set_audio_backend("soundfile")
/venv/lib/python3.10/site-packages/torch_audiomentations/utils/io.py:27: UserWarning: torchaudio._backend.set_audio_backend has been deprecated. With dispatcher enabled, this function is no-op. You can remove the function call.
  torchaudio.set_audio_backend("soundfile")
torchvision is not available - cannot save figures
Lightning automatically upgraded your loaded checkpoint from v1.5.4 to v2.1.2. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint ../cache/torch/whisperx-vad-segmentation.bin`
Model was trained with pyannote.audio 0.0.1, yours is 3.1.0. Bad things might happen unless you revert pyannote.audio to 0.x.
Model was trained with torch 1.10.0+cu102, yours is 2.1.1+cu118. Bad things might happen unless you revert torch to 1.x.
>>Performing transcription...
>>Performing alignment...
>>Performing diarization...
Traceback (most recent call last):
  File "/venv/bin/whisperx", line 8, in <module>
    sys.exit(cli())
  File "/venv/lib/python3.10/site-packages/whisperx/transcribe.py", line 218, in cli
    diarize_model = DiarizationPipeline(use_auth_token=hf_token, device=device)
  File "/venv/lib/python3.10/site-packages/whisperx/diarize.py", line 19, in __init__
    self.model = Pipeline.from_pretrained(model_name, use_auth_token=use_auth_token).to(device)
  File "/venv/lib/python3.10/site-packages/pyannote/audio/core/pipeline.py", line 88, in from_pretrained
    config_yml = hf_hub_download(
  File "/venv/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "/venv/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 1210, in hf_hub_download
    os.makedirs(storage_folder, exist_ok=True)
  File "/usr/local/lib/python3.10/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/local/lib/python3.10/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/local/lib/python3.10/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/local/lib/python3.10/os.py", line 225, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/.cache'
```

Steps to reproduce by manually building the Docker image: 
```bash 
cd /mnt/c/ubuntu

git clone --recursive https://github.com/jim60105/docker-whisperX.git

cd /mnt/c/ubuntu/docker-whisperX

docker build --build-arg LANG=en --build-arg WHISPER_MODEL=small -t testing/whisperx:small-en .

cd /mnt/c/temp/ubuntu/whisperx-test
docker run --gpus all -it -v ".:/app" testing/whisperx:small-en -- --diarize --hf_token "XXXXX" audio.mp3

Matplotlib created a temporary cache directory at /tmp/matplotlib-mdfth0sn because the default path (/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
/venv/lib/python3.10/site-packages/pyannote/audio/core/io.py:43: UserWarning: torchaudio._backend.set_audio_backend has been deprecated. With dispatcher enabled, this function is no-op. You can remove the function call.
  torchaudio.set_audio_backend("soundfile")
/venv/lib/python3.10/site-packages/torch_audiomentations/utils/io.py:27: UserWarning: torchaudio._backend.set_audio_backend has been deprecated. With dispatcher enabled, this function is no-op. You can remove the function call.
  torchaudio.set_audio_backend("soundfile")
torchvision is not available - cannot save figures
Lightning automatically upgraded your loaded checkpoint from v1.5.4 to v2.1.2. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint ../cache/torch/whisperx-vad-segmentation.bin`
Model was trained with pyannote.audio 0.0.1, yours is 3.1.0. Bad things might happen unless you revert pyannote.audio to 0.x.
Model was trained with torch 1.10.0+cu102, yours is 2.1.1+cu118. Bad things might happen unless you revert torch to 1.x.
>>Performing transcription...
>>Performing alignment...
>>Performing diarization...
Traceback (most recent call last):
  File "/venv/bin/whisperx", line 8, in <module>
    sys.exit(cli())
  File "/venv/lib/python3.10/site-packages/whisperx/transcribe.py", line 218, in cli
    diarize_model = DiarizationPipeline(use_auth_token=hf_token, device=device)
  File "/venv/lib/python3.10/site-packages/whisperx/diarize.py", line 19, in __init__
    self.model = Pipeline.from_pretrained(model_name, use_auth_token=use_auth_token).to(device)
  File "/venv/lib/python3.10/site-packages/pyannote/audio/core/pipeline.py", line 88, in from_pretrained
    config_yml = hf_hub_download(
  File "/venv/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "/venv/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 1210, in hf_hub_download
    os.makedirs(storage_folder, exist_ok=True)
  File "/usr/local/lib/python3.10/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/local/lib/python3.10/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/local/lib/python3.10/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/local/lib/python3.10/os.py", line 225, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/.cache'
```

**Comment by jim60105** [comment]
Should be fixed with https://github.com/jim60105/docker-whisperX/commit/500db66c6ea704470b0a246b49e44236b2a5b771
Please pull the new image after this CI finish.
https://github.com/jim60105/docker-whisperX/actions/runs/7042601644

**Comment by randyburden** [comment]
The issue has been resolved. Thanks!
